### ISSUE TITLE
login method breaks backward compatibility

### ISSUE THREAD

**Issue by plfort** [jameshartig/GroovesharkAPI-PHP#15]
Hello,
Previous version of "login" method requires password has md5, but new version of login call "authenticate" method that hash AGAIN the password..
In addition, it is impossible to overload the current code because of private arguments like wsSscret and wsKey.

**Comment by jameshartig** [comment]
Not sure what you mean about the overloading, but can you file a separate bug for that?

UPDATE: You can pass the key/secret to the constructor. They shouldn't change throughout the life of the instance, so there was no need to make the public/protected.

**Comment by plfort** [comment]
Thank you for your reactivity !
To fix the previous issue, I wanted to override the makeCall method but I could not because it uses wsSession and wsKey and their are private to the parent class.

**Comment by jameshartig** [comment]
Why would you want to override that method? And it makeCall is private as well.

**Comment by plfort** [comment]
I wanted to override "login" method, to make it I extended your class.
I had to call makeCall from my "login" method, but I could not because it is private to parent class.
In cascade, I could not override makeCall because it uses private attributes (wsSecret and wsSecret)from parent class.
