### ISSUE TITLE
Runtime Notice

### ISSUE THREAD

**Issue by ckdarby** [jameshartig/GroovesharkAPI-PHP#4]
``` PHP

Severity: Runtime Notice

Message: Declaration of gsUser::authenticate() should be compatible with gsAPI::authenticate(gsUser $user)

Filename: grooveshark/gsUser.php

Line Number: 388

```

**Comment by jameshartig** [comment]
That doesn't make much since considering gsAPI accepts a gsUser object.

**Comment by ckdarby** [comment]
childClass::customMethod() has different arguments, or a different access level (public/private/protected) than parentClass::customMethod().

``` PHP
//gsUser.php
    public function authenticate() {


//gsAPI.php
    public function authenticateUser(gsUser $user){
        if (!$this->session){
```

**Comment by ckdarby** [comment]
Just for reference sake I wanted to mention that I am running the latest of master(7784a6dbeec90db4819e2a030755d0fb0e603fc3)

**Comment by jameshartig** [comment]
Unfortunately there is no backwards-compatible way to fix this. The gsUser objects have a authenticate() call, which is just a mask to the gsAPI method and the authenticate() call on gsAPI definitely can't be changed. I don't think it's worth it to possibly break existing apps to fix a E_STRICT run-time notice.

**Comment by jameshartig** [comment]
Also, I'm rewriting this library this weekend so if you want to update, this issue will be gone. It will not be backwards compatible though. I'm going to write up some docs on converting but the new version should be a lot better.

**Comment by ckdarby** [comment]
I was just starting my project so I can put it off until the rewrite.

Thanks!

**Comment by jameshartig** [comment]
@ckdarby sorry for the extreme delay. In case you're still interested, I've uploaded the new version. This runtime notice shouldn't happen anymore either.

**Comment by ckdarby** [comment]
@fastest963 Thanks :)
